server:
  port: 8091

spring:
  application:
    name: cadastro-usuarios

  datasource:
    url: jdbc:mysql://localhost:3306/ecomerce
    username: alves
    password: alves2596
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect


api:
  urlValidaCpf: "https://api.invertexto.com/v1/validator?token=8608|dnSzKD5l6gTqxdUzivgZ8wrlyZAbKeK0&value="
  type: "&type=cpf"
  urlValidaCep: "https://viacep.com.br/ws/%s/json/"

jwt:
  secret: "YWt1ZmFzaHZqZGF2YnNkdHV5dGF2c2hhdmR5YXN0ZmRhdGdzdmRrYWpzaHR5ZmRheWdzY3ZkbXNoamZnc2Rmczk4NzQ2MjE2Nzk="