server:
  port: 8092

spring:
  application:
    name: login

  datasource:
    url: jdbc:mysql://localhost:3306/ecomerce
    username: alves
    password: alves2596
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: "YWt1ZmFzaHZqZGF2YnNkdHV5dGF2c2hhdmR5YXN0ZmRhdGdzdmRrYWpzaHR5ZmRheWdzY3ZkbXNoamZnc2Rmczk4NzQ2MjE2Nzk="
